module.exports = [
    {
        "nome": "Cavaleiros do Ocidente",
        "img": "img/priorados/05.jpg",
        "imgext": "https://github.com/victorhundo/DeMolayPB-Android/blob/master/app/src/main/assets/img/priorados/05.jpg?raw=true",
        "fundacao": "1994-07-21T03:00:00.000Z",
        "instalacao": "1994-10-15T03:00:00.000Z",
        "iccnome": "Iago Marques de Oliveira Batista",
        "icctelefone": "-",
        "iccemail": "iagobatistadm@gmail.com",
        "protonome": "Carlos Antônio Soares Júnior",
        "prototelefone": "-",
        "protoemail": "jrsoares39@hotmail.com"
    },
    {
        "nome": "Nobres Cavaleiros Condutores da Luz",
        "img": "img/priorados/37.jpg",
        "imgext": "https://github.com/victorhundo/DeMolayPB-Android/blob/master/app/src/main/assets/img/priorados/37.jpg?raw=true",
        "fundacao": "1998-03-14T03:00:00.000Z",
        "instalacao": "1998-04-26T03:00:00.000Z",
        "iccnome": "Pedro João Cruz Neto",
        "icctelefone": "(83) 9651-2019",
        "iccemail": "pedro.netosb@hotmail.com",
        "protonome": "Jordan dos Santos Ferreira",
        "prototelefone": "(83) 9639-7645",
        "protoemail": "ferreira.jordan8@gmail.com"
    },
    {
        "nome": "Nobres Cavaleiros do Sertão",
        "img": "img/priorados/98.jpg",
        "imgext": "https://github.com/victorhundo/DeMolayPB-Android/blob/master/app/src/main/assets/img/priorados/98.jpg?raw=true",
        "fundacao": "2002-11-23T03:00:00.000Z",
        "instalacao": "2003-03-30T03:00:00.000Z",
        "iccnome": "Luan Alencar",
        "icctelefone": "(83) 9650-5175",
        "iccemail": "luan.alencar@live.com",
        "protonome": "Luis Henrique Batista Gadelha de Oliveira",
        "prototelefone": "(83) 9145-7955",
        "protoemail": "luis_henrique53@hotmail.com"
    },
    {
        "nome": "Deus, Patria e Família",
        "img": "img/priorados/110.jpg",
        "imgext": "https://github.com/victorhundo/DeMolayPB-Android/blob/master/app/src/main/assets/img/priorados/110.jpg?raw=true",
        "fundacao": "2004-07-04T03:00:00.000Z",
        "instalacao": "2004-07-04T03:00:00.000Z",
        "iccnome": "Ewerton Guilherme Alves De Sousa",
        "icctelefone": "(83) 9860-9737",
        "iccemail": "ewertoncah624@gmail.com",
        "protonome": "José Manoel Ferreira De Lima Cruz",
        "prototelefone": "(83) 9637-5381",
        "protoemail": "josemanoel.demolay@hotmail.com"
    },
    {
        "nome": "Franklin Cardoso de Sousa",
        "img": "img/priorados/145.jpg",
        "imgext": "https://github.com/victorhundo/DeMolayPB-Android/blob/master/app/src/main/assets/img/priorados/145.jpg?raw=true",
        "fundacao": "2009-09-23T03:00:00.000Z",
        "instalacao": "2010-02-20T03:00:00.000Z",
        "iccnome": "Yoseph Vaz",
        "icctelefone": "(83) 9964-0889",
        "iccemail": "yosephvaz@gmail.com",
        "protonome": "Kaio José",
        "prototelefone": "(83) 9664-1592",
        "protoemail": "kaiojose_@hotmail.com"
    },
    {
        "nome": "Francisco de Assis Florentino Filho",
        "img": "img/priorados/166.jpg",
        "imgext": "https://github.com/victorhundo/DeMolayPB-Android/blob/master/app/src/main/assets/img/priorados/166.jpg?raw=true",
        "fundacao": "2012-01-16T03:00:00.000Z",
        "instalacao": "2012-02-05T03:00:00.000Z",
        "iccnome": "Lucas Ravy Pereira Gomes de Souza",
        "icctelefone": "(83) 9113-1089",
        "iccemail": "lucasravy@yahoo.com.br",
        "protonome": "Whelley Pereira Izidro",
        "prototelefone": "(83) 9879-6613",
        "protoemail": "whelley_p@hotmail.com"
    }
]